### PR TITLE
solving issue #9

### PR DESCRIPTION
**Pull request by sreyan-ghosh**
**ISSUE** #9 solved completely.

**Changes Made**
1. Used `sphinx` to create the documentation for the project. 
2. There seems to be a path routing problem for `python-sphinx` but all docstrings have been parsed.
3. The documentation is available at `docs/build/html/index.html`
4. Theme applied is of ReadTheDocs, can be changes in the `conf.py` file in the `docs` directory.

**NOTE**
Please consider this submission as a part of **Hacktoberfest 2021** and add the `hacktoberfest-accepted` label.

### CODE REVIEW

**Comment by LonelyCat124** [comment]
Hiya, thanks for doing this.

You've pushed a lot of files in this commit that don't need to be in this PR I think.
Can you remove your `.venv` folder and the resulting documentation, and if there isn't one, replace the documentation with a Makefile so I can build it myself and plug it into GHA?

Once thats done I can do a proper review of this :)

**Comment by sreyan-ghosh** [comment]
Hi, I made some changes, do have a look 😃

**Comment by LonelyCat124** [comment]
Thanks! Can you also remove the `docs/_build` output from the Makefile and then I'll have a proper look tomorrow

**Comment by sreyan-ghosh** [comment]
I'm sorry I didn't understand. What outputs do you want me to remove?

**Comment by LonelyCat124** [comment]
The built documentation, only the Makefile will be needed as the documentation will be built with a Github Action and put on readthedocs automatically soon.

**Comment by sreyan-ghosh** [comment]
Hi @LonelyCat124, have a look

**Comment by LonelyCat124** [comment]
Sorry for delay, its first on my list to look at tomorrow!

**Comment by LonelyCat124** [comment]
Hi - looks good. Could you move your copyright from the project `conf.py` to headers of the individual files you edited?

There are few more tweaks I'll make myself post-merging. 

I'll run this through the workflow just to make sure it hasn't broken anything else, if it works and the asked copyright move is done then I'll accept it and merge it.

**Comment by sreyan-ghosh** [comment]
that copyright is an auto-generated one. It was made when I used `sphinx-quickstart`. I can remove my name from it altogether if that's what you are asking. I'll just keep `stfc` then? There's no need for the name under individual files in my opinion. 

Here is how it will look after changing:

```py
project = 'HartreeParticleDSL'
copyright = '2021, stfc'
author = 'stfc'
```

I'll make a commit with these changes; if this is not what you wanted, tell me and I'll make another commit.

**Comment by LonelyCat124** [comment]
Sure, its up to you re: copyrights in header. Otherwise looks great to me, thanks! Will add the tag now and squash & merge

**Pull request merged**
